server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: /Users/honeybees/PROJ/spring/spring-cloud/config-server/src/main/resources/config/test-server
