server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - /Users/honeybees/PROJ/spring/spring-cloud/config-server/src/main/resources/config/test-server
            - /Users/honeybees/PROJ/spring/spring-cloud/config-server/src/main/resources/config/licensingservice
  application:
    name: configserver


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
